---
title: "Data Visualization"
Author: 'Mst. Shamima Hossain'
date: "`r format (Sys.time (), '%Y/%m/%d') `"
output: word_document
---

```{r include = FALSE}
# Preprocessing, such as loading a package. Do not display in reports.
  ifile <- "winequality-red.csv"
  
# Read csv file into data frame
  d <-read.csv (ifile, check.names = F)
  # If you want to use the $notation for data frames, check.names=T
  # If you don't want the symbols in the header to be converted, check.names=F
  
opts_chunk$set(fig.width=3, fig.height=2.7, echo=FALSE, cache=FALSE, message=FALSE)
```

# Overview

Visualize the data in `r ifile`.

## Basic Statistics

Minimum, median, maximum, average, and quartile.

It might be good to add the standard deviation and the number of data.

```{r}
tab <- NULL
for(i in colnames(d)){
  x <- d[,i]
  if(is.numeric(x) && i != "Grade" & i != "producer code"){
    tab <- rbind(tab, round(summary(x), digits=4))
    rownames(tab)[nrow(tab)] <- i
  } else {
    tab2 <- table(x)
	tab2<- as.data.frame(tab2)
	colnames(tab2)[1]<-i
	x1 <- kable(tab2, format = "pandoc")
    cat(x1, sep = "\n")
	cat(sep="\n")
	}
	
}
kable(tab)
```

## Visibility per Item

Numerical data is shown as a histogram, and category data is shown as a bar graph.

```{r}
par(mgp=c(2, 1, 0), mar=c(3, 3, 3, 1), xaxs="i", yaxs="i", cex=.7)
for(i in colnames(d)){
  x <- d[,i]
  if(is.numeric(x) && i != "Grade" & i != "producer code"){
     h<- hist(x, main=i, breaks=30,xlab="")
     xfit<-seq(min(x),max(x),length=80)
     yfit<-dnorm(xfit,mean=mean(x),sd=sd(x))
     yfit <- yfit*diff(h$mids[1:2])*length(x)
     lines(xfit, yfit, col="red")}
  else      barplot(table(x), main=i, xlab="")
}
```
```{r, cache=FALSE}
x1 <- NULL
x2 <- NULL
x3 <- NULL

for(i in 1:nrow(d)){
    if (d[i,13]=="Satisfactory")  x1 <- rbind(x1,d[i,])
    else if (d[i,13]=="Good")  x2 <- rbind(x2,d[i,])
    else  x3 <- rbind(x3,d[i,])
}

```

```{r, cache=FALSE}

par(mgp=c(2, 1, 0), mar=c(3, 3, 3, 1), cex=0.66)
for (i in colnames(d) ){
  if(is.numeric(d[,i]) && i != "Grade" && i != "producer code"){
     plot(d[,i],jitter(d[,"Grade"]),xlab=i,
          ylab="quality", col="blue", cex=0.8, cex.lab=1.3)
     abline(lm(d[, "Grade"] ~ d[,i]),lty=2,lwd=2)
    }
}

```

```{r}
par(mgp=c(2, 1, 0), mar=c(3, 3, 3, 1), xaxs="i", yaxs="i", cex=.7)
for(i in colnames(d)){
  x <- d[,i]
  if(is.numeric(d[,i]) && i != "Grade" && i != "producer code"){
        for (j in (1:length(x))){
	     if (x[j]!=0) x[j]<- log10(x[j])}
        h<- hist(x, main=i, breaks=30,xlab="")}
}
for(i in colnames(d)){
  x <- d[,i]
  if (i != "Grade" && i != "producer code" && i != "rating" && i!="Type" && i != "Producer Name"){
      boxplot(x~Grade,data=d,main="Different boxplots for each grade",xlab="Grade",
            ylab=i,col="orange",border="brown")}
}

```

```{r}
tartaricgreater14 <- subset(d, TartaricAcid >= 14)
tartaricless14 <- subset(d, TartaricAcid < 14)
boxplot(TartaricAcid~Grade,data=tartaricgreater14,main="Greater Than 14",xlab="Grade",
            ylab="Tartaric Acid ",col="orange",border="brown")
by(tartaricgreater14[,"TartaricAcid"] , tartaricgreater14[,"Grade"],table)
boxplot(TartaricAcid~Grade,data=tartaricless14,main="Less Than 14",xlab="Grade",
            ylab="Tartaric Acid ",col="orange",border="brown")
```

```{r}
aceticgreater14 <- subset(d, Acetic >= 1.05)
aceticless14 <- subset(d, Acetic < 1.05)
boxplot(Acetic~Grade,data=aceticgreater14,main="Greater Than 1.05",xlab="Grade",
            ylab="Acetic Acid ",col="orange",border="brown")
by(aceticgreater14[,"Acetic"] , aceticgreater14[,"Grade"],table)
boxplot(Acetic~Grade,data=aceticless14,main="Less Than 1.05",xlab="Grade",
            ylab="Acetic Acid ",col="orange",border="brown")
```

```{r}
par(mgp=c(1, 1, 0), mar=c(3, 3, 3, 1))
ggplot() + geom_point(data = x2, aes(x = Citric, y = Acetic, shape = as.factor(Grade), color = as.factor(Grade))) 
ggplot() + geom_point(data = x2, aes(x = Citric, y = TartaricAcid, shape = as.factor(Grade), color = as.factor(Grade))) 
ggplot() + geom_point(data = x2, aes(x = Citric, y = TartaricAcid, shape = as.factor(Grade), color = as.factor(Grade))) 

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(data = d,
       aes(y = TartaricAcid , x = Acetic,
           color = as.factor(Grade))) +
  #geom_point(alpha = 0.8, size = 0.5) +
  geom_smooth(method = "lm", se = FALSE,size=2)  +
  #facet_wrap(~rating) +
  scale_color_brewer(type='seq',
                   guide=guide_legend(title='Quality'))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(data = d,
       aes(y = TartaricAcid , x = Citric,
           color = as.factor(Grade))) +
  #geom_point(alpha = 0.8, size = 0.5) +
  geom_smooth(method = "lm", se = FALSE,size=2)  +
  #facet_wrap(~rating) +
  scale_color_brewer(type='seq',
                   guide=guide_legend(title='Quality'))
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(data = d,
       aes(y = Acetic , x = Citric,
           color = as.factor(Grade))) +
  #geom_point(alpha = 0.8, size = 0.5) +
  geom_smooth(method = "lm", se = FALSE,size=2)  +
  #facet_wrap(~rating) +
  scale_color_brewer(type='seq',
                   guide=guide_legend(title='Quality'))
```
```{r}
sugargreater6.8 <- subset(d, Residualsugar >= 6.8)
sugarless6.8 <- subset(d, Residualsugar < 6.8)


ggplot(sugargreater6.8, aes(x=Grade, y=Residualsugar, fill=as.factor(Grade))) +
    geom_boxplot(alpha=0.7) +
    stat_summary(fun.y=mean, geom="point", shape=20, size=4, color="red", fill="red") +
    theme(legend.position="none") +
    scale_fill_brewer(palette="Set1")

ggplot(sugarless6.8, aes(x=Grade, y=Residualsugar, fill=as.factor(Grade))) +
    geom_boxplot(alpha=0.7) +
    stat_summary(fun.y=mean, geom="point", shape=20, size=4, color="red", fill="red") +
    theme(legend.position="none") +
    scale_fill_brewer(palette="Set1")
```